//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsForJoe.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public string UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ResumeFileName { get; set; }
        public string BaristaImage { get; set; }
        public bool IsEmployed { get; set; }
        public string Bio { get; set; }
    }
}
